### ISSUE TITLE
how to config grafana

### ISSUE THREAD

**Issue by zhouzhuoCSUFT** [plazonic/gpfs-exporter#1]
Hi！
      I'm interested in this project, but I'm not familiar with grafana, and I want to know how to configure grafana and display it  on dashboard after configuring exporter.
I have tried to add Prometheus data source, but there is an error
![image](https://user-images.githubusercontent.com/37490415/224459624-2f5d6a58-ab08-4533-9098-6e02d3dc8766.png)

**Comment by plazonic** [comment]
Hello,

that's a bit of out of scope of this particular project but I'd say make sure first that prometheus is running and that you can query it. E.g. you should be able to go to the http://myprometheus.server.url/graph and lookup some basic metrics, either the gpfs ones or the built ones (prometheus_build_info - if you configured prometheus to scrape itself).

I added a basic prometheus server setup example and I updated grafana json dashboard with one that relies on only one server (it previously mistakenly used trickster as well). That might help but otherwise refer to Grafana and Prometheus docs (e.g. https://prometheus.io/docs/visualization/grafana/)

JP
